### ISSUE TITLE
Loading obj_v3 model / ValueError: NodeDef expected inputs 'variant

### ISSUE THREAD

**Issue by kevinyena** [JunweiLiang/Object_Detection_Tracking#35]
Hello, when i try to load de obj_v3.pb model into memory with a new code and i have this error : 

Traceback (most recent call last):
  File "C:\Users\kyena\Anaconda3\envs\py37\lib\site-packages\tensorflow\python\framework\importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs 'variant, int32' do not match 1 inputs specified; Op<name=TensorListStack; signature=input_handle:variant, element_shape:int32 -> tensor:element_dtype; attr=element_dtype:type; attr=num_elements:int,default=-1>; NodeDef: {{node fastrcnn_predictions/map/TensorArrayV2Stack/TensorListStack}} 

would you know how to fix this please ? 

the way i load is here : 

```
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.compat.v1.GraphDef()
    with tf.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.compat.v1.import_graph_def(od_graph_def, name='')
    sess = tf.Session(graph=detection_graph)
```

and i'am using tf 1.14.0
    
thank you

**Comment by JunweiLiang** [comment]
If you are using this model (https://aladdin-eax.inf.cs.cmu.edu/shares/diva_obj_detect_models/models/obj_v3.pb), it is expected to have errors since it is frozen using tf 1.13 (which is noted [here](https://github.com/JunweiLiang/Object_Detection_Tracking#models)). Try downloading this model file instead: https://aladdin-eax.inf.cs.cmu.edu/shares/diva_obj_detect_models/models/obj_v3_model.tgz
