### ISSUE TITLE
Question about your map evaluation code

### ISSUE THREAD

**Issue by houzhijian** [JunweiLiang/Object_Detection_Tracking#6]
Hi, JunweiLiang:
&nbsp;&nbsp;  &nbsp;&nbsp;   If I am right, your ap evaluation code is here
https://github.com/JunweiLiang/Object_Detection_Tracking/blob/8af1178fe2743c9954fa85a22a14fa6ca46776b0/utils.py#L553-L569
&nbsp;&nbsp; &nbsp;&nbsp;   However,  it is not a standard ap evaluation for object detection adopted by PASCAL VOC or COCO dataset. I think your implementation is the standard ap evaluation for information retrieval.

&nbsp;&nbsp; &nbsp;&nbsp;  It is incomparable with your given result if I use PASCAL VOC evaluation. So I think you can clarify it in your readme.file.

**Comment by JunweiLiang** [comment]
No, you are wrong.

Have you tried using both my evaluation code and [pycocotool](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py) on the 200k ActEV validation set? Do you even know the average precision equation/why they are different/how they are different?

 The difference is in the computation of recall thresholds. The actual score difference is within 1%, and it is smaller given larger datasets. And obviously, the two code are linearly correlated given the same outputs. If you had done any engineering, you would know which one to choose when the pycocotool takes a lot more RAM and time to run.

I certainly have no obligation to "clarify" anything for you.

**Comment by houzhijian** [comment]
Hi, JunweiLiang:
&nbsp;&nbsp;&nbsp;&nbsp;  Thanks for your quick response and clear explanation. 
&nbsp;&nbsp;&nbsp;&nbsp;  I am just quite confused about the difference between your code and the coco evaluation code. Yeah, I have not tried to compare the real result of those two.  :sweat_smile:.
&nbsp;&nbsp;&nbsp;&nbsp;  Sorry for the distraction. I didn't mean to challenge you.

**Comment by JunweiLiang** [comment]
That's OK. I guess it is because I'm having a bad day. Actually, you do remind me of making the evaluation code exactly the same as COCO's. I will do this in September. Basically replacing the compute_AP function to a more efficient version of [cocotool](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L353).

Cheers,
Junwei

**Comment by houzhijian** [comment]
Hi, JunweiLiang:
&nbsp;&nbsp;&nbsp;&nbsp;    I have one more thing to consult.
&nbsp;&nbsp;&nbsp;&nbsp;    As your readme.md file puts it, Cascade RCNN doesn't help (IOU=0.5). I'm using IOU=0.5 in my evaluation since the original annotations are not "tight" bounding boxes.
&nbsp;&nbsp;&nbsp;&nbsp;    I wonder whether it is necessary to use COCO AP at IoU=.50:.05:.95 as primary challenge metric like COCO for this dataset. how about AP at IoU=.50 (PASCAL VOC metric)  as primary challenge metric for this dataset?  What do you think?

**Comment by JunweiLiang** [comment]
I'm using IOU=.5 in all evaluations in ActEV. You can set IOU=.5 in pycocotools as well. So this is basically the VOC metric.

As I stated, you can't really use IoU=.95 in this dataset since the ground truth bounding boxes are not accurate/tight. From the making-a-real-application-that-works standpoint, it makes no real difference between IOU=.5 and IOU=.75, as humans can hardly tell IOU=.3 from IOU=.5 as stated by the YOLOv3 paper.
